### ISSUE TITLE
GTS error when loading configs

### ISSUE THREAD

**Issue by Zimon4eR** [NickImpact/GTS#10]
Error: https://gist.github.com/anonymous/ccc587b66153ce0040665dc1990f30ff
Tested on: spongeforge-1.12.2-2555-7.1.0-BETA-2825 and spongeforge-1.12.2-2555-7.0.0-BETA-2802 - same result

**Comment by NickImpact** [comment]
`# +----------------------------------------------------------------------------------------------+ #
# |                                           Blacklist                                          | #
# +----------------------------------------------------------------------------------------------+ #
blacklist {
    # List the names of the pokemon you wish to block from entry into the GTS
    pokemon=[
        ""
    ]

    # Specify these here by their item types. So, for example, a pokeball would be translated as:
    # pixelmon:poke_ball
    items=[
        ""
    ]
}`

This was a configurate bug. They initialized an empty list as null rather than a simple empty list. Just update your config settings for this section to look like such.

**Comment by Zimon4eR** [comment]
Thank you
