### ISSUE TITLE
Adding items/pokemon

### ISSUE THREAD

**Issue by m1zark** [NickImpact/GTS#2]
GTS display the error message that you have reached your deposit limit even though you haven't. It still adds the item. Does this for items and pokemon.

https://prnt.sc/huiur2

**Comment by NickImpact** [comment]
This was due to a mistake in the default message configuration. If you take a look, the message there runs what is essentially the exact same as the max-listings option.

Just alter your setting to something like such:
**"{{gts_prefix}} &7Your &a{{listing_name}} &7has been added to the market!"**

Then with the max-listings option, just add the prefix if you'd like
