### ISSUE TITLE
YouKit shows thrown NPE's

### ISSUE THREAD

**Issue by XakepSDK** [NickImpact/GTS#22]
https://puu.sh/A7Cxx/fbd48c178d.png
Here: https://github.com/NickImpact/GTS/blob/master/src/main/java/com/nickimpact/gts/ui/MainUI.java#L144

**Comment by NickImpact** [comment]
Gonna need a little more info to this, such as what scenarios cause said NPE's

**Comment by XakepSDK** [comment]
I don't know, how this happens. I have just profiled one server. Just add
null check after getting item from list.

**Comment by NickImpact** [comment]
Unfortunately, the problem isn't as simple as such. That method call shouldn't encounter null whatsoever. Therefore, a null check there would actually hurt the system more than it'd help. For this to be effective, we need to evaluate how you could possibly be receiving null values from that method call.

**Comment by PixelmonPRO** [comment]
@NickImpact https://gist.github.com/PixelmonPRO/be1e950f210879c1bf98d2781223e104

**Comment by NickImpact** [comment]
@PixelmonPRO What is that gist for?

**Comment by XakepSDK** [comment]
https://puu.sh/A9CLM/cc92209e6f.png
https://puu.sh/A9CMJ/3454fe5db3.png

**Comment by NickImpact** [comment]
From what I can tell, the null pointer you seem to have is not caused by any of the code you think it is. As I've stated, this seems to be tracing all the way back into the text parsing for Nucleus. So perhaps the null encounter you are finding is from Nucleus and not actually GTS (Considering the method calls you are highlighting from GTS should never encounter a null pointer, only exception being that the plugin loaded improperly).

**Comment by NickImpact** [comment]
Marking this as closed as there has been no response.
