### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by Levy26** [NickImpact/GTS#38]
Hello,
I was using your plugin and the same has a problem.

Some times it starts and works normally, in another it generates an error at startup and when I enter the server as non-existent / gts command.

Here is the log:
https://hastebin.com/alekefuboc.apache

**Comment by NickImpact** [comment]
Did Impactor error on start up?

**Comment by Levy26** [comment]
I did not see any errors in the Impactor

https://hastebin.com/tegokopuci.rb

**Comment by NickImpact** [comment]
Try prefixing the Impactor jar with _a, so it reads _aImpactor... From what I can tell with the error, the issue suggests Impactor didn't launch properly, or the config failed to initialize

**Comment by demonte4509ui** [comment]
im having the same issue...impactor starts just fine and it says gts is starting up and works but when I log in and do /gts it says unknown command

**Comment by DrZoddiak** [comment]
I can Confirm that prefixing with `a` works fine.

This is a little perplexing however since Sponge _should_ be loading it first given you've listed it as a dependency.
https://github.com/NickImpact/GTS/blob/master/plugin/src/main/java/me/nickimpact/gts/GTS.java#L83

https://github.com/NickImpact/Impactor/blob/master/src/main/java/com/nickimpact/impactor/CoreInfo.java#L14

I am curious if this is perhaps because of the way you're calling it for some reason?

https://github.com/NickImpact/Impactor/blob/master/src/main/java/com/nickimpact/impactor/ImpactorCore.java#L40

Or if it's just a sponge bug for some reason.

**Comment by NickImpact** [comment]
If I can get these errors reposted via pastebin, that'd be great. The errors seem to no longer be able to be read, as in the pages look blank.

**Comment by DrZoddiak** [comment]
https://gist.github.com/DrZoddiak/ba5fb2c5ac06decbb76f6c62ad48d102

**Comment by NickImpact** [comment]
Gonna be uploading a new Impactor version, as I suspect I have a small change I missed between the API that is causing GTS to fail. I'll update this comment with the Ore link once I got that uploaded. If you could try with that version and see how it goes, that'd be great.

**Comment by NickImpact** [comment]
Ore is down apparently, or it just doesn't want me to upload the new version. So, this is why we have discord.

https://cdn.discordapp.com/attachments/510206580957118480/530115560126677016/Impactor-S7.1.0-1.4.1.jar

**Comment by DrZoddiak** [comment]
Just ran it, and It appears to work as expected.
