### ISSUE TITLE
Command: /gts ignore

### ISSUE THREAD

**Issue by MageFX** [NickImpact/GTS#74]
**What are you trying to do?**
Once you ignore gts listings you can't toggle it back on

**Describe the solution you'd like**
Add toggle feature

**Describe alternatives you've considered**
As above.

**Anything else that might help?**
As above.

**Comment by NickImpact** [comment]
Replaced with a per player "Player Settings" configuration. Allows for control of all different types of output rather than everything at once ignored. For instance, you can see when you've been outbid, but still ignore new listings being created.

Will close when commit finalizing menu and functionality is done.
